### ISSUE TITLE
Create dev branch

### ISSUE THREAD

**Issue by abhishekpatelmc** [engineering4-0/website#1]
- @rajcrk could you create a dev branch so we could raise PR to the dev branch instead of the main

**Comment by rajcrk** [comment]
Thanks. That's a good idea.

Created a new branch `dev`. Please raise PRs to dev.

**Comment by rajcrk** [comment]
Closing the issue as dev branch is created.

**Comment by abhishekpatelmc** [comment]
- Thank you
