### ISSUE TITLE
Update the home page to list out all the volunteers of the club (Tech Team)

### ISSUE THREAD

**Issue by rajcrk** [engineering4-0/website#4]

**Comment by AshvinjeetSingh** [comment]
Hi Raj

I have couple of questions
1)Can I design it in any style in respect to website or is there any existing design for it
2)Are all the members volunteers as well or are they are the new people that joined club like me and ameya 
3)if not from where can I find the details for that

**Comment by rajcrk** [comment]
1. The website currently uses a react UI component library called Carbon Design by IBM (https://react.carbondesignsystem.com/?path=/docs/experimental-unstable-fluidtextinput--password-input). You can refer that for the style of the website. But in terms of the design make sure that it follows the existing design patter. Right now we have the board members of the club listed.

![Screen Shot 2023-04-28 at 5 44 16 PM](https://user-images.githubusercontent.com/15966586/235259404-6efaf652-52e2-40e9-b18d-725b3a9df81c.png)

Create another section that is similar to this and provide the title of the section as Volunteers of the Club. 

2 and 3. The volunteers are new people that just joined the club. Yes it includes you and ameya. I believe that you might need details regarding their LinkedIn URL and profile picture. I'll work on getting that to you.

Let me know if you have any more questions.
